name: Default Node CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: lints
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 14 Environment . . .
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Build Docker Image "crucible-standard/cryptoget"
        run: docker build -t crucible-standard/cryptoget .
      - name: Run The Lints . . .
        run: docker run crucible-standard/cryptoget npm run test:lint
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v2
      - name: Setup Node 14 Environment . . .
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Build Docker Image "crucible-standard/cryptoget"
        run: docker build -t crucible-standard/cryptoget .
      - name: Run The Tests . . .
        run: docker run crucible-standard/cryptoget npm run test

