name: Node Integration Process

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  ci:
    name: npm run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely..
        uses: actions/checkout@v2
      - name: Setup Node 12.x Environment...
        uses: actions/setup-node@v1
        with: 
          node-version: 12.x
          registry-url: https://npm.pkg.github.com/
          scope: "@wh-iterabb-it"
      - name: Installing Dependencies...
        working-directory: .
        run: npm install
        env:
          GIT_NPM_AUTH_TOKEN: ${{secrets.GIT_NPM_AUTH_TOKEN}}
      - name: Running npm run test...
        working-directory: .
        run: npm run test
