name: Default Node CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: lints
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v4
      - name: Setup Node 20 Environment . . .
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Build Docker Image "crucible-standard/cryptoget"
        run: docker build -t crucible-standard/cryptoget .
      - name: Run The Lints . . .
        run: docker run crucible-standard/cryptoget npm run test:lint
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v4
      - name: Setup Node 20 Environment . . .
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Build Docker Image "crucible-standard/cryptoget"
        run: docker build -t crucible-standard/cryptoget .
      - name: Run The Tests . . .
        run: docker run crucible-standard/cryptoget npm run test
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Commits Securely . . .
        uses: actions/checkout@v4
      - name: Setup Node 20 Environment . . .
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies . . .
        working-directory: .
        run: npm ci
      - name: Run The Tests . . .
        run: npm run test:coverage 
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
